Repository dooboolab/hackatalk, pull requests merged in 2019-12, with the labels that each got.

#43 [Feature] Add alert message and navigate screen when sign-in with google
  __mocks__/expo-facebook.ts
  __mocks__/expo-google-sign-in.ts
  jest.config.js
  src/components/screen/Login.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  test/jestSetup.ts
Labels: feature

#47 [Feature] Get photo info by Shooting Camera or selecting album
  STRINGS.ts
  package.json
  src/components/screen/Chat.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/__tests__/Chat.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/shared/__tests__/GiftedChat.test.tsx
  src/providers/index.tsx
  src/utils/ImagePicker.ts
  src/utils/__tests__/ImagePicker.test.ts
  yarn.lock
Labels: feature

#63 [Feature] PinchZoomView image viewer with zoomable and multiple Images support
  package.json
  src/components/shared/PinchZoomView.tsx
  src/components/shared/__tests__/PinchZoomView.test.tsx
  src/components/shared/__tests__/__snapshots__/PinchZoomView.test.tsx.snap
  yarn.lock
Labels: feature

#69 [Migration] Remove local theme provider and use dooboo-ui theming instead
  package.json
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/RootStackNavigator.tsx
  src/components/screen/Chat.tsx
  src/components/screen/FindPW/index.tsx
  src/components/screen/Login.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/SignUp/index.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  src/components/shared/ChatListItem.tsx
  src/components/shared/ChatroomListItem.tsx
  src/components/shared/ProfileModal.tsx
  src/components/shared/StatusBar.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/UserListItem.test.tsx
  src/providers/ThemeProvider.tsx
  src/providers/__tests__/ThemeProvider.test.tsx
  src/providers/index.tsx
  src/styled.d.ts
  src/theme.ts
  src/types/index.ts
  test/testUtils.tsx
  yarn.lock
Labels: migration

#62 [Feature] Dark Mode Automatic Recognition
  app.sample.json
  package.json
  src/App.tsx
  src/components/screen/Friend.tsx
  src/components/screen/__tests__/Chat.test.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/Message.test.tsx
  src/components/screen/__tests__/NotFound.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/Setting.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ChatListItem.test.tsx
  src/components/shared/__tests__/ChatroomListItem.test.tsx
  src/components/shared/__tests__/EmptyListItem.test.tsx
  src/components/shared/__tests__/GiftedChat.test.tsx
  src/components/shared/__tests__/PinchZoomView.test.tsx
  src/components/shared/__tests__/ProfileModal.test.tsx
  src/components/shared/__tests__/StatusBar.test.tsx
  src/components/shared/__tests__/TextInput.test.tsx
  src/components/shared/__tests__/__snapshots__/ChatroomListItem.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/EmptyListItem.test.tsx.snap
  yarn.lock
Labels: feature

#78 [Upgrade] expo to sdk 36
  .vscode/settings.json
  app.sample.json
  jest.config.js
  package.json
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/RootStackNavigator.tsx
  src/components/screen/FindPW/index.tsx
  src/components/screen/Login.tsx
  src/components/screen/Message.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/SignUp/index.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/Message.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/PinchZoomView.tsx
  src/types/index.ts
  src/utils/__tests__/ImagePicker.test.ts
  yarn.lock
Labels: upgrade

#58 [Feature] Add a section list and changePassword Modal to Setting screen
  STRINGS.ts
  __mocks__/expo-facebook.ts
  package.json
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/screen/ChangePw/index.tsx
  src/components/screen/ChangePw/styles.ts
  src/components/screen/FindPw/index.tsx
  src/components/screen/FindPw/styles.ts
  src/components/screen/Login.tsx
  src/components/screen/Setting.tsx
  src/components/screen/Setting/index.tsx
  src/components/screen/Setting/styles.ts
  src/components/screen/SignUp/index.tsx
  src/components/screen/__tests__/ChangePw.test.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/Setting.test.tsx
  src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Setting.test.tsx.snap
  src/components/shared/ProfileModal.tsx
  src/providers/AuthUserProvider.tsx
  src/providers/index.tsx
  src/types/index.ts
  test/jestSetup.ts
  test/testUtils.tsx
  yarn.lock
Labels: feature

#81 Remove dup [ThemeType] definition locally
  src/components/shared/StatusBar.tsx
  src/providers/__tests__/ThemeProvider.test.tsx
  src/providers/index.tsx
  test/testUtils.tsx
Labels: enhancement, typings

#77 [Feature] Add agreement message and link to terms
  STRINGS.ts
  package.json
  src/components/navigation/AuthStackNavigator.tsx
  src/components/screen/SignIn.tsx
  src/components/screen/WebView.tsx
  src/components/screen/__tests__/WebView.test.tsx
  src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/WebView.test.tsx.snap
  src/types/index.ts
  yarn.lock
Labels: feature

#84 Improve navigation typings and remove unused screen
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/RootStackNavigator.tsx
  src/components/screen/ChangePw/index.tsx
  src/components/screen/Chat.tsx
  src/components/screen/FindPw.tsx
  src/components/screen/Message.tsx
  src/components/screen/NotFound.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/Setting/index.tsx
  src/components/screen/SignIn.tsx
  src/components/screen/SignUp.tsx
  src/components/screen/Temp.tsx
  src/components/screen/WebView.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/WebView.test.tsx.snap
  src/components/shared/ChatListItem.tsx
  src/types/index.ts
  test/jestSetup.ts
Labels: enhancement, typings
