Repository dooboolab/hackatalk, pull requests merged in 2019-10, with the labels that each got.

#24 Enh/ui fix
  package.json
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/screen/Chat.tsx
  src/components/screen/FindPw.tsx
  src/components/screen/Friend.tsx
  src/components/screen/Login.tsx
  src/components/screen/NotFound.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/Setting.tsx
  src/components/screen/SignUp.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/NotFound.test.tsx
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/ChatListItem.tsx
  src/components/shared/ChatroomListItem.tsx
  src/components/shared/ProfileModal.tsx
  src/components/shared/TextInput.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/StatusBar.test.tsx
  src/contexts/__tests__/index.test.tsx
  yarn.lock
Labels: enhancement

#28 bugfix: Minor ui fix
  .circleci/config.yml
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/screen/Chat.tsx
  src/contexts/__tests__/index.test.tsx
  src/styled.d.ts
  src/theme.ts
Labels: bugfix

#23 Feature/SearchUser
  .vscode/settings.json
  src/components/screen/FindPw.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/__snapshots__/SearchUser.test.tsx.snap
  src/components/shared/ProfileModal.tsx
  src/theme.ts
Labels: feature

#31 Fix Button's layout bug
  src/components/screen/__tests__/__snapshots__/Chat.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
Labels: bugfix
