Repository dooboolab/hackatalk, pull requests merged in 2019-09, with the labels that each got.

#4 resolve conflicts when executing android simulator
  package.json
  src/providers/AppProvider.tsx
  src/utils/Icons.ts
Labels: setup

#5 Logo change
  .gitignore
  app.sample.json
  assets/icon.png
  assets/icons/icon.png
  assets/icons/icon@2x.png
  assets/icons/icon@3x.png
  assets/splash.png
  package.json
  yarn.lock
Labels: enhancement

#8 Customized main tab header to put gradient as in design
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/providers/AppProvider.tsx
  src/styled.d.ts
  src/theme.ts
Labels: enhancement

#6 'typescript-eslint/recommended' 추가
  .eslintrc.js
  src/components/screen/FindPw.tsx
  src/components/shared/Button.tsx
  src/theme.ts
Labels: enhancement

#17 Simplified eslint rules by managing in one place
  .eslintrc.js
  package.json
  yarn.lock
Labels: Related eslint, enhancement
