Repository dooboolab/hackatalk, pull requests merged in 2019-11, with the labels that each got.

#21 Signup (front-only) /infrastructure related to @testing-library/react-native
  .vscode/settings.json
  STRINGS.ts
  jest.config.js
  package.json
  src/components/screen/Chat.tsx
  src/components/screen/FindPw.tsx
  src/components/screen/Login.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/SignUp.tsx
  src/components/screen/SignUp/index.tsx
  src/components/screen/SignUp/styles.tsx
  src/components/screen/__tests__/Chat.test.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/Message.test.tsx
  src/components/screen/__tests__/NotFound.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/Setting.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/Chat.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SearchUser.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ChatListItem.test.tsx
  src/components/shared/__tests__/ChatroomListItem.test.tsx
  src/components/shared/__tests__/UserListItem.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ChatListItem.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/UserListItem.test.tsx.snap
  src/contexts/__tests__/index.test.tsx
  src/theme.ts
  test/setupTest.js
  test/test-utils.tsx
  yarn.lock
Labels: config, feature

#45 [WIP] migration: react navigation v5
  package.json
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/RootStackNavigator.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/Chat.tsx
  src/components/screen/FindPw.tsx
  src/components/screen/Login.tsx
  src/components/screen/Message.tsx
  src/components/screen/NotFound.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/Setting.tsx
  src/components/screen/SignUp/index.tsx
  src/components/screen/SignUp/styles.tsx
  src/components/screen/Temp.tsx
  src/components/screen/__tests__/Chat.test.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/Message.test.tsx
  src/components/screen/__tests__/NotFound.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/Setting.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ChatListItem.test.tsx
  src/components/shared/__tests__/ChatroomListItem.test.tsx
  src/components/shared/__tests__/EmptyListItem.test.tsx
  src/components/shared/__tests__/ProfileModal.test.tsx
  src/components/shared/__tests__/StatusBar.test.tsx
  src/components/shared/__tests__/TextInput.test.tsx
  src/components/shared/__tests__/UserListItem.test.tsx
  src/providers/ThemeProvider.tsx
  src/providers/index.tsx
  src/types/index.ts
  src/utils/createCtx.ts
  src/utils/testUtils.tsx
  test/test-utils.tsx
  yarn.lock
Labels: migration

#46 Update app.sample.json
  .github/PULL_REQUEST_TEMPLATE.md
  app.sample.json
Labels: documentation

#48 Enhance typings for [Chat] message
  .eslintrc.js
  src/components/screen/Chat.tsx
  src/components/screen/Message.tsx
  src/components/screen/__tests__/__snapshots__/Chat.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/shared/ChatListItem.tsx
  src/components/shared/ChatroomListItem.tsx
  src/types/index.ts
Labels: enhancement, typings

#49 Enhance typings for [Chat] message
  src/types/index.ts
Labels: enhancement, typings

#50 Findpw component & test codes
  STRINGS.ts
  package.json
  src/components/navigation/AuthStackNavigator.tsx
  src/components/screen/FindPW/index.tsx
  src/components/screen/FindPW/styles.ts
  src/components/screen/FindPw.tsx
  src/components/screen/Login.tsx
  src/components/screen/SignUp/index.tsx
  src/components/screen/SignUp/styles.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/__snapshots__/Chat.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Login.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Temp.test.tsx.snap
  src/components/shared/Button.tsx
  src/components/shared/TextInput.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/TextInput.test.tsx.snap
  yarn.lock
Labels: feature, waiting for response

#57 Move prettier settings, enhance auto-import behavior
  .prettierrc.js
  .vscode/settings.json
Labels: enhancement

#55 refactor context & reducer pattern to provider & functional pattern
  src/App.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/screen/Friend.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/screen/__tests__/__snapshots__/SearchUser.test.tsx.snap
  src/components/shared/ProfileModal.tsx
  src/components/shared/StatusBar.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ChatroomListItem.test.tsx
  src/components/shared/__tests__/EmptyListItem.test.tsx
  src/components/shared/__tests__/StatusBar.test.tsx
  src/components/shared/__tests__/TextInput.test.tsx
  src/components/shared/__tests__/UserListItem.test.tsx
  src/components/shared/__tests__/__snapshots__/UserListItem.test.tsx.snap
  src/contexts/__tests__/__snapshots__/index.test.tsx.snap
  src/contexts/__tests__/index.test.tsx
  src/contexts/index.tsx
  src/providers/ProfileModalProvider.tsx
  src/providers/__tests__/ThemeProvider.test.tsx
  src/providers/__tests__/__snapshots__/ThemeProvider.test.tsx.snap
  src/providers/index.tsx
  src/reducers/ProfileModalReducer.tsx
  src/reducers/themeReducer.tsx
  src/utils/testUtils.tsx
Labels: refactor

#66 [Refactor] Folder structure and testUtils dir
  src/components/screen/Chat.tsx
  src/components/screen/Login.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/SignUp/styles.tsx
  src/components/screen/__tests__/Chat.test.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/Login.test.tsx
  src/components/screen/__tests__/Message.test.tsx
  src/components/screen/__tests__/NotFound.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/Setting.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/Temp.test.tsx
  src/components/shared/ChatListItem.tsx
  src/components/shared/ChatroomListItem.tsx
  src/components/shared/ProfileModal.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ChatListItem.test.tsx
  src/components/shared/__tests__/ChatroomListItem.test.tsx
  src/components/shared/__tests__/EmptyListItem.test.tsx
  src/components/shared/__tests__/ProfileModal.test.tsx
  src/components/shared/__tests__/StatusBar.test.tsx
  src/components/shared/__tests__/TextInput.test.tsx
  src/components/shared/__tests__/UserListItem.test.tsx
  src/types/index.ts
  test/testUtils.tsx
Labels: refactor

#42 [Feature] Float [ProfileModal] on profile click
  .prettierrc.js
  src/components/screen/Chat.tsx
  src/components/screen/__tests__/Chat.test.tsx
  src/components/screen/__tests__/__snapshots__/Chat.test.tsx.snap
  src/components/shared/ChatListItem.tsx
  src/components/shared/__tests__/ChatListItem.test.tsx
  src/components/shared/__tests__/__snapshots__/ChatListItem.test.tsx.snap
Labels: enhancement, feature
