Repository dooboolab/hackatalk, pull requests merged in 2020-10, with the labels that each got.

#271 Add Ramda Support
  server/package.json
  server/src/resolvers/User/mutation.ts
  server/src/services/ChannelService.ts
  server/yarn.lock
Labels: enhancement, refactor

#272 Initial chattings integration
  client/schema.graphql
  client/src/components/screen/Message.tsx
  client/src/components/shared/ChannelListItem.tsx
  client/src/components/shared/MessageListItem.tsx
  client/src/components/shared/UserListItem.tsx
  client/src/components/shared/__tests__/UserListItem.test.tsx
  client/src/providers/ProfileModalProvider.tsx
  client/src/types/graphql.ts
  client/src/types/index.ts
  server/src/models/Channel.ts
  server/src/models/Message.ts
  server/src/resolvers/Channel/query.ts
  server/src/resolvers/Message/index.ts
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/Message/query.ts
  server/tests/e2e/resolvers/message.test.ts
  server/tests/e2e/setup/queries/Message.ts
Labels: feature

#275 Fix Disappearing Modal Issue
  client/src/__generated__/ProfileModalFindOrCreatePrivateChannelMutation.graphql.ts
  client/src/components/navigation/MainStackNavigator.tsx
  client/src/components/screen/Friend.tsx
  client/src/components/screen/Message.tsx
  client/src/components/screen/SearchUser.tsx
  client/src/components/screen/__tests__/Message.test.tsx
  client/src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  client/src/components/shared/GiftedChat.tsx
  client/src/components/shared/ProfileModal.tsx
  client/src/components/shared/__tests__/ProfileModal.test.tsx
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  client/src/providers/ProfileModalProvider.tsx
Labels: bugfix, enhancement

#278 Update packages
  server/@types/typegen-nexus-plugin-prisma/index.d.ts
  server/package.json
  server/src/schema.ts
  server/yarn.lock
Labels: update packages

#279 Add onPress Handler to Profile Modal Buttons
  client/src/__generated__/ProfileModalAddFriendMutation.graphql.ts
  client/src/__generated__/ProfileModalDeleteFriendMutation.graphql.ts
  client/src/components/shared/ProfileModal.tsx
  client/src/components/shared/__tests__/ProfileModal.test.tsx
Labels: enhancement, feature

#280 Prepare notifications
  client/src/App.tsx
  client/src/components/screen/SignIn.tsx
  server/src/resolvers/Message/mutation.ts
Labels: feature

#281 Adjust Message Input Flex Styles
  client/src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  client/src/components/shared/GiftedChat.tsx
  client/src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
Labels: enhancement

#284 Upgrade packages and migrated to prisma 2.8.1
  server/package.json
  server/src/models/Channel.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/services/ChannelService.ts
  server/src/services/UserService.ts
  server/yarn.lock
Labels: migration

#283 Fix Android Notification Issue
  client/app.config.js
  client/src/App.tsx
  client/src/__generated__/AppUserQuery.graphql.ts
  client/src/__generated__/ChannelComponent_channel.graphql.ts
  client/src/__generated__/ChannelLastMessageQuery.graphql.ts
  client/src/__generated__/Channels.graphql.ts
  client/src/__generated__/ChannelsQuery.graphql.ts
  client/src/__generated__/MessageComponent_message.graphql.ts
  client/src/__generated__/MessagePaginationQuery.graphql.ts
  client/src/__generated__/MessagesQuery.graphql.ts
  client/src/components/screen/Channel.tsx
  client/src/components/screen/Friend.tsx
  client/src/components/screen/Message.tsx
  server/src/resolvers/Message/query.ts
  server/src/services/NotificationService.ts
Labels: feature

#285 Add diagram
  server/README.md
Labels: documentation, hacktoberfest-accepted

#286 Update packages
  client/package.json
  client/src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  client/src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/ChannelCreate.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ErrorView.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/MessageListItem.test.tsx.snap
  client/yarn.lock
  server/package.json
  server/yarn.lock
Labels: update packages

#287 Remove snapshots since this is auto generated in ci
  client/.gitignore
  client/src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/ChannelCreate.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/NotFound.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/WebView.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/CheckBox.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/EmptyListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ErrorView.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/MessageListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/SearchTextInput.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/SocialSignInButton.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/TextInput.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/UserListItem.test.tsx.snap
Labels: environment, testing

#288 Minor ui bug fixes
  client/package.json
  client/src/components/screen/Channel.tsx
  client/src/components/screen/Message.tsx
  client/src/components/shared/ChannelListItem.tsx
  client/src/components/shared/GiftedChat.tsx
  client/yarn.lock
Labels: bugfix
