Repository dooboolab/hackatalk, pull requests merged in 2020-09, with the labels that each got.

#225 Updated ProfileUpdate image upload request with useMutation
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/schema.graphql
  client/src/__generated__/ProfileUpdateSingleUploadMutation.graphql.ts
  client/src/components/screen/ProfileUpdate.tsx
  client/src/components/screen/__tests__/ProfileUpdate.test.tsx
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  client/src/relay/fetch.ts
  client/src/types/graphql.ts
  server/src/types/resolvers/Upload/mutation.ts
  server/src/utils/azure.ts
Labels: bugfix, enhancement

#230 [Server] add ChannelService
  server/src/services/ChannelService.ts
  server/src/types/resolvers/Channel/mutation.ts
Labels: enhancement

#235 Ask Notification Permission on Login
  client/src/App.tsx
  client/src/components/screen/SignIn.tsx
  client/src/utils/noti.ts
Labels: enhancement

#239 Upgrade/packages relay experimental
  client/package.json
  client/yarn.lock
Labels: update packages

#240 Update packages
  client/package.json
  client/src/components/navigation/MainStackNavigator.tsx
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  client/src/providers/AuthProvider.tsx
  client/src/providers/ProfileModalProvider.tsx
  client/yarn.lock
  server/package.json
  server/src/types/resolvers/Message/mutation.ts
  server/src/types/resolvers/User/mutation.ts
  server/tests/resolvers/channel.test.ts
  server/tests/setup/testSetup.ts
  server/yarn.lock
Labels: update packages

#209 Adding media query to support responsive design
  client/package.json
  client/src/App.tsx
  client/src/components/screen/SignIn.tsx
  client/src/hooks/useResponsiveDesign.tsx
  client/src/theme.ts
  client/src/utils/media.ts
  client/yarn.lock
Labels: need discussion

#233 Add Error Message on Wrong Password in Login
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/src/components/screen/SignIn.tsx
  node_modules/.yarn-integrity
  yarn.lock
Labels: enhancement

#243 Add channels field resolver to [User]
  server/src/types/models/User.ts
  server/src/types/resolvers/Channel/mutation.ts
  server/tests/resolvers/channel.test.ts
  server/tests/resolvers/user.test.ts
  server/tests/setup/queries/Channel.ts
  server/tests/setup/queries/User.ts
Labels: enhancement

#245 Integrate findOrCreatePrivateChannel and reveal user name as a title
  client/schema.graphql
  client/src/__generated__/MainStackNavigatorFindOrCreatePrivateChannelMutation.graphql.ts
  client/src/components/navigation/MainStackNavigator.tsx
  client/src/components/screen/Message.tsx
  client/src/components/screen/SignIn.tsx
  client/src/components/screen/__tests__/Message.test.tsx
  client/src/components/shared/ProfileModal.tsx
  client/src/types/graphql.ts
  client/test/jestSetup.ts
Labels: integration

#244 Exclude web platform from expo-notifications
  client/.gitignore
  client/src/utils/noti.ts
Labels: bugfix

#247 Migrate to dooboo-ui@0.0.17
  client/package.json
  client/src/components/screen/FindPw.tsx
  client/src/components/screen/Message.tsx
  client/src/components/screen/ProfileUpdate.tsx
  client/src/components/screen/SignIn.tsx
  client/src/components/screen/SignUp.tsx
  client/src/components/screen/VerifyEmail.tsx
  client/src/components/shared/SocialSignInButton.tsx
  client/yarn.lock
Labels: migration

#249 Add cloud deploy config
  .github/workflows/deploy-web-app.yml
  CONTRIBUTING.md
  client/.env.sample
  client/.gitignore
  client/README.md
  client/__mocks__/expo-auth-session.ts
  client/app.config.js
  client/app.json
  client/babel.config.js
  client/config.sample.ts
  client/config.ts
  client/package.json
  client/src/components/screen/SignIn.tsx
  client/src/components/screen/__tests__/SignIn.test.tsx
  client/src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  client/src/components/shared/SocialSignInButton.tsx
  client/src/components/shared/__tests__/SocialSignInButton.test.tsx
  client/test/jestSetup.ts
  client/yarn.lock
Labels: deploy, workflow

#254 Hot fix on queries after applying connections
  client/schema.graphql
  client/src/__generated__/FriendFriendsQuery.graphql.ts
  client/src/components/screen/Friend.tsx
  client/src/components/screen/__tests__/FindPw.test.tsx
  client/src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  client/src/types/graphql.ts
  server/src/types/models/User.ts
  server/src/types/resolvers/Channel/query.ts
  server/src/types/resolvers/User/query.ts
  server/tests/resolvers/channel.test.ts
  server/tests/setup/queries/Channel.ts
  server/tests/setup/queries/User.ts
Labels: hotfix, migration

#255 Integrate pagination to [Channel] screen
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/schema.graphql
  client/src/__generated__/ChannelComponent_channel.graphql.ts
  client/src/__generated__/Channels.graphql.ts
  client/src/__generated__/ChannelsQuery.graphql.ts
  client/src/components/screen/Channel.tsx
  client/src/components/screen/SearchUser.tsx
  client/src/components/screen/__tests__/Channel.test.tsx
  client/src/components/shared/ChannelListItem.tsx
  client/src/types/graphql.ts
Labels: feature, integration

#246 Migrate profile update
  client/src/__generated__/ProfileUpdateMutation.graphql.ts
  client/src/components/screen/ProfileUpdate.tsx
  client/src/components/screen/__tests__/ProfileUpdate.test.tsx
Labels: client, refactor

#257 Specify Messages on No Content
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/src/components/screen/Channel.tsx
  client/src/components/screen/Friend.tsx
  client/src/components/screen/SearchUser.tsx
Labels: enhancement

#256 Create message with cache invalidation
  client/assets/langs/en.json
  client/schema.graphql
  client/src/__generated__/ChannelComponent_channel.graphql.ts
  client/src/__generated__/Channels.graphql.ts
  client/src/__generated__/ChannelsQuery.graphql.ts
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/components/screen/Channel.tsx
  client/src/components/screen/Message.tsx
  client/src/components/screen/SignIn.tsx
  client/src/components/shared/ChannelListItem.tsx
  client/src/relay/index.ts
  client/src/types/graphql.ts
  node_modules/.yarn-integrity
  server/src/app.ts
  server/src/services/ChannelService.ts
  server/src/types/models/Channel.ts
  server/src/types/resolvers/Channel/mutation.ts
  server/src/types/resolvers/Channel/query.ts
  server/src/types/resolvers/Message/mutation.ts
  yarn.lock
Labels: feature

#224 Made UserService / moved signInWithSocialAccount to UserService
  server/src/services/UserService.ts
  server/src/types/resolvers/User/mutation.ts
Labels: refactor

#268 Upgrade server packages
  server/package.json
  server/tests/setup/testSetup.ts
  server/yarn.lock
Labels: server, update packages

#270 More linting
  server/src/apis/root.ts
  server/src/app.ts
  server/src/permissions/index.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/User/mutation.ts
  server/src/server.ts
  server/src/utils/auth.ts
  server/src/utils/azure.ts
  server/src/utils/pagination.ts
  server/tests/integration/setup/resolvers/User.ts
Labels: eslint

#267 Fix/expo sdk 39 migration
  client/__mocks__/react-native-reanimated.js
  client/jest.config.js
  client/package.json
  client/src/components/navigation/__tests__/AuthStackNavigator.test.tsx
  client/src/components/navigation/__tests__/RootStackNavigator.test.tsx
  client/src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  client/src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  client/src/components/screen/__tests__/ChangePw.test.tsx
  client/src/components/screen/__tests__/Channel.test.tsx
  client/src/components/screen/__tests__/FindPw.test.tsx
  client/src/components/screen/__tests__/Friend.test.tsx
  client/src/components/screen/__tests__/Message.test.tsx
  client/src/components/screen/__tests__/NotFound.test.tsx
  client/src/components/screen/__tests__/ProfileUpdate.test.tsx
  client/src/components/screen/__tests__/SignIn.test.tsx
  client/src/components/screen/__tests__/SignUp.test.tsx
  client/src/components/screen/__tests__/VerifyEmail.test.tsx
  client/src/components/screen/__tests__/WebView.test.tsx
  client/src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/NotFound.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/WebView.test.tsx.snap
  client/src/components/shared/__tests__/ChannelListItem.test.tsx
  client/src/components/shared/__tests__/CheckBox.test.tsx
  client/src/components/shared/__tests__/EmptyListItem.test.tsx
  client/src/components/shared/__tests__/ErrorView.test.tsx
  client/src/components/shared/__tests__/MessageListItem.test.tsx
  client/src/components/shared/__tests__/SearchTextInput.test.tsx
  client/src/components/shared/__tests__/SocialSignInButton.test.tsx
  client/src/components/shared/__tests__/StatusBar.test.tsx
  client/src/components/shared/__tests__/TextInput.test.tsx
  client/src/components/shared/__tests__/UserListItem.test.tsx
  client/src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/CheckBox.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/EmptyListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ErrorView.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/MessageListItem.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/SearchTextInput.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/SocialSignInButton.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/StatusBar.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/TextInput.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/UserListItem.test.tsx.snap
  client/src/providers/__tests__/DeviceProvider.test.tsx
  client/src/providers/__tests__/ThemeProvider.test.tsx
  client/src/providers/__tests__/__snapshots__/DeviceProvider.test.tsx.snap
  client/src/providers/__tests__/__snapshots__/ThemeProvider.test.tsx.snap
  client/src/utils/__tests__/ComponentWrapper.test.tsx
  client/test/jestSetup.js
  client/test/jestSetup.ts
  client/yarn.lock
Labels: migration, testing
