Repository dooboolab/hackatalk, pull requests merged in 2020-12, with the labels that each got.

#323 Prisma upgrade to 2.13.0 and db migration
  server/package.json
  server/prisma/migrations/20201120070839-init/README.md
  server/prisma/migrations/20201120070839-init/schema.prisma
  server/prisma/migrations/20201120070839-init/steps.json
  server/prisma/migrations/20201212012053_init/migration.sql
  server/prisma/migrations/migrate.lock
  server/tests/e2e/testSetup.ts
  server/yarn.lock
Labels: migration

#325 Upgrade expo to sdk 40
  client/.env.sample
  client/.eslintignore
  client/metro.config.js
  client/package.json
  client/schema.graphql
  client/src/App.tsx
  client/src/apis/upload.ts
  client/src/components/screen/LicenseAgreement.tsx
  client/src/components/screen/Settings.tsx
  client/src/components/screen/SignIn.tsx
  client/src/components/screen/__tests__/SignIn.test.tsx
  client/src/components/shared/SocialSignInButton.tsx
  client/src/components/shared/UserListItem.tsx
  client/src/relay/fetch.ts
  client/test/jestSetup.ts
  client/yarn.lock
  server/src/schema.ts
Labels: migration, upgrade

#326 Upload file directly from multer to azure-blob-storage
  client/src/apis/upload.ts
  server/__mocks__/azure-storage.ts
  server/__mocks__/multer-azure-blob-storage.ts
  server/dotenv/dev.env
  server/dotenv/test.env
  server/package.json
  server/src/apis/root.ts
  server/yarn.lock
Labels: bugfix, enhancement, server

#327 Apply client named file when uploading files
  client/src/apis/upload.ts
  server/src/apis/root.ts
Labels: enhancement

#329 Migrate [@nexus/schema] to [nexus]
  server/package.json
  server/src/models/AuthPayload.ts
  server/src/models/BlockedUser.ts
  server/src/models/Channel.ts
  server/src/models/Friend.ts
  server/src/models/Membership.ts
  server/src/models/Message.ts
  server/src/models/Notification.ts
  server/src/models/Reaction.ts
  server/src/models/Reply.ts
  server/src/models/Report.ts
  server/src/models/Scalar.ts
  server/src/models/User.ts
  server/src/resolvers/BlockedUser/mutation.ts
  server/src/resolvers/BlockedUser/query.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/resolvers/Channel/query.ts
  server/src/resolvers/Friend/mutation.ts
  server/src/resolvers/Friend/query.ts
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/Message/query.ts
  server/src/resolvers/Notification/mutation.ts
  server/src/resolvers/Notification/query.ts
  server/src/resolvers/Report/mutation.ts
  server/src/resolvers/Report/query.ts
  server/src/resolvers/Upload/mutation.ts
  server/src/resolvers/User/mutation.ts
  server/src/resolvers/User/query.ts
  server/src/resolvers/User/subscription.ts
  server/src/schema.ts
  server/yarn.lock
Labels: migration, update packages

#330 Update packages
  .circleci/config.yml
  client/README.md
  client/STRINGS.ts
  client/package.json
  client/tsconfig.jest.json
  client/tsconfig.json
  client/yarn.lock
  server/package.json
  server/yarn.lock
Labels: update packages

#331 Fix Styled Components Type Issue
  client/package.json
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement

#333 Update packages
  client/package.json
  server/package.json
  server/yarn.lock
Labels: client, server, update packages
