Repository dooboolab/hackatalk, pull requests merged in 2020-08, with the labels that each got.

#177 Applied connection plugin and impl on user connection
  client/src/components/screen/__tests__/FindPw.test.tsx
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  server/package.json
  server/src/schema.ts
  server/src/types/resolvers/Friend/index.ts
  server/src/types/resolvers/Friend/query.ts
  server/src/types/resolvers/User/query.ts
  server/src/utils/pagination.ts
  server/yarn.lock
Labels: feature, server

#181 Integrate signUp and email verification resolver in client
  client/package.json
  client/src/__generated__/SignUpMutation.graphql.ts
  client/src/__generated__/SignUpSendVerificationMutation.graphql.ts
  client/src/components/screen/SignUp.tsx
  client/src/components/screen/__tests__/SignIn.test.tsx
  client/src/components/screen/__tests__/SignUp.test.tsx
  client/web-build/register-service-worker.js
  client/yarn.lock
Labels: client, integration

#182 Upgrade server packages
  server/package.json
  server/tests/setup/testSetup.ts
  server/yarn.lock
Labels: update packages

#185 Fix signUp screen scroll on ios
  client/src/components/screen/SignUp.tsx
  client/src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
Labels: client, enhancement, ui

#189 Implement addFriend and deleteFriend resolvers
  server/.vscode/settings.json
  server/src/types/models/Friend.ts
  server/src/types/models/User.ts
  server/src/types/resolvers/Friend/index.ts
  server/src/types/resolvers/Friend/mutation.ts
  server/src/types/resolvers/Friend/query.ts
  server/src/types/resolvers/User/mutation.ts
  server/src/types/resolvers/index.ts
  server/tests/resolvers/friend.test.ts
  server/tests/resolvers/upload.test.ts
  server/tests/resolvers/user.test.ts
  server/tests/setup/queries/Friend.ts
  server/tests/setup/queries/User.ts
  server/tests/setup/queries/index.ts
Labels: feature

#184 Fix email verification log
  server/src/app.ts
  server/src/types/resolvers/User/mutation.ts
  server/src/utils/auth.ts
Labels: enhancement, refactor, server

#186 block already verified email in 'verified_email' route
  server/src/app.ts
Labels: enhancement

#193 Make email titles translatable
  server/locales/en.json
  server/locales/ko.json
  server/src/types/resolvers/User/mutation.ts
Labels: enhancement

#200 Fix Image Styles
  client/src/components/navigation/MainStackNavigator.tsx
  client/src/components/navigation/MainTabNavigator.tsx
  client/src/components/screen/ProfileUpdate.tsx
Labels: bugfix, ui

#198 Use SENDGRID_EMAIL Environment Variable
  server/dotenv/dev.env
  server/dotenv/test.env
  server/src/types/resolvers/User/mutation.ts
Labels: client, environment

#201 Check sign up form validity immediately
  client/src/components/screen/SignUp.tsx
Labels: enhancement

#203 Resolve Conflicting expo-font Versions
  client/package.json
  client/yarn.lock
Labels: dependencies

#204 Migrate from bcrypt-nodejs to bcrypt
  server/package.json
  server/src/utils/auth.ts
  server/yarn.lock
Labels: enhancement, migration

#199 Run relay-compiler Again
  client/schema.graphql
  client/src/__generated__/AppUserQuery.graphql.ts
  client/src/__generated__/ProfileUpdateMeQuery.graphql.ts
  client/src/__generated__/SignInAppleMutation.graphql.ts
  client/src/__generated__/SignInEmailMutation.graphql.ts
  client/src/__generated__/SignUpMutation.graphql.ts
  client/src/__generated__/SignUpSendVerificationMutation.graphql.ts
  client/src/__generated__/SocialSignInButtonFacebookSignInMutation.graphql.ts
  client/src/__generated__/SocialSignInButtonGoogleSignInMutation.graphql.ts
  client/src/__generated__/VerifyEmailMutation.graphql.ts
  client/src/types/graphql.ts
Labels: client, relay

#196 Keyboard Automatic Search while Input Implemented
  client/assets/langs/en.json
  client/src/components/screen/ChannelCreate.tsx
  client/src/components/screen/Message.tsx
Labels: enhancement, feature

#223 improve test codes
  server/tests/resolvers/User/mutation/signInEmail.test.ts
  server/tests/resolvers/User/mutation/signInWithApple.test.ts
  server/tests/resolvers/User/mutation/signInWithFacebook.test.ts
  server/tests/resolvers/User/mutation/signInWithGoogle.test.ts
  server/tests/resolvers/friend.test.ts
  server/tests/resolvers/user.test.ts
Labels: enhancement, testing

#218 Add A Helper Class to Format Nested Providers
  client/src/App.tsx
  client/src/utils/ComponentWrapper.tsx
  client/src/utils/__tests__/ComponentWrapper.test.tsx
Labels: enhancement

#228 Applied relay cursor pagination in [SearchUser]
  client/.eslintrc.js
  client/schema.graphql
  client/src/__generated__/SearchUserComponent_user.graphql.ts
  client/src/__generated__/SearchUsersPaginationQuery.graphql.ts
  client/src/__generated__/SearchUsersQuery.graphql.ts
  client/src/components/screen/Channel.tsx
  client/src/components/screen/SearchUser.tsx
  client/src/components/shared/UserListItem.tsx
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/UserListItem.test.tsx.snap
  client/src/types/graphql.ts
  server/src/types/resolvers/User/mutation.ts
  server/src/types/resolvers/User/query.ts
Labels: feature
