Repository dooboolab/hackatalk, pull requests merged in 2020-03, with the labels that each got.

#117 Initial migration on splash screen
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/dooboolab/hackatalk/MainActivity.java
  android/app/src/main/res/drawable/bootsplash.xml
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  app.json
  assets/bootsplash_logo.png
  assets/bootsplash_logo@2x.png
  assets/bootsplash_logo@3x.png
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/HackaTalk/AppDelegate.m
  ios/HackaTalk/Base.lproj/LaunchScreen.xib
  ios/HackaTalk/BootSplash.storyboard
  ios/HackaTalk/Images.xcassets/BootSplashLogo.imageset/Contents.json
  ios/HackaTalk/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  ios/HackaTalk/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  ios/HackaTalk/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  ios/HackaTalk/Images.xcassets/Contents.json
  ios/HackaTalk/Images.xcassets/SplashImage.imageset/Contents.json
  ios/HackaTalk/Info.plist
  ios/Podfile.lock
  package.json
  src/App.tsx
  yarn.lock
Labels: migration

#119 Upgrade packages
  .gitignore
  .ncurc.json
  package.json
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  src/components/screen/ChangePw.tsx
  src/components/screen/__tests__/Message.test.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ChannelCreate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SearchUser.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  src/components/shared/GiftedChat.tsx
  src/components/shared/MessageListItem.tsx
  src/components/shared/ProfileModal.tsx
  src/components/shared/SearchTextInput.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/StatusBar.test.tsx
  src/components/shared/__tests__/__snapshots__/ErrorView.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/SearchTextInput.test.tsx.snap
  yarn.lock
Labels: enhancement, upgrade

#120 [Feature][Apple Authentication]
  __mocks__/expo-apple-authentication.ts
  src/components/screen/SignIn/index.tsx
  src/components/screen/SignIn/mobile.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
Labels: feature
