Repository dooboolab/hackatalk, pull requests merged in 2020-07, with the labels that each got.

#151 Workaround for typing issue in #150
  client/src/App.tsx
Labels: typings

#153 Migrate to fetchQuery since preloadQuery wont handle error
  .gitignore
  client/src/App.tsx
  client/src/components/screen/SignIn.tsx
  client/src/providers/AuthProvider.tsx
  client/src/relay/fetch.ts
Labels: enhancement

#154 Remove relay from AuthProvider and manage in single environment on the app.
  client/src/App.tsx
  client/src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  client/src/providers/AuthProvider.tsx
  client/src/providers/index.tsx
  client/src/relay/index.ts
  client/test/setupTest.js
Labels: enhancement

#155 Add singleUpload mutation for multipart upload
  server/package.json
  server/schema.graphql
  server/src/permissions/index.ts
  server/src/schema.ts
  server/src/types/resolvers/Upload/index.ts
  server/src/types/resolvers/Upload/mutation.ts
  server/src/types/resolvers/index.ts
  server/tests/upload.test.ts
  server/yarn.lock
Labels: feature

#161 Change preloadQuery to fetch
  client/src/components/screen/ProfileUpdate.tsx
  client/src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  client/src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  client/src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
Labels: enhancement

#163 Enhance localization in auth flow
  server/html/email_verification.html
  server/html/password_changed.html
  server/html/password_reset.html
  server/locales/en.json
  server/locales/ko.json
  server/src/permissions/index.ts
  server/src/types/resolvers/User/mutation.ts
  server/src/utils/auth.ts
Labels: enhancement

#164 UI bug fixes in change password
  server/html/password_changed.html
  server/locales/en.json
  server/locales/ko.json
  server/src/app.ts
Labels: bugfix, enhancement

#165 Implement social signins - facebook, google
  server/package.json
  server/schema.graphql
  server/src/types/models/Scalar.ts
  server/src/types/resolvers/User/mutation.ts
  server/src/utils/auth.ts
  server/src/utils/error.ts
  server/tests/setup/queries.ts
  server/tests/user.test.ts
  server/yarn.lock
Labels: feature

#166 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#171 Update generated path for schema.graphql
  server/schema.graphql
  server/src/schema.ts
Labels: enhancement

#172 Add and fix an explanation of CONTRIBUTING.md in server's setup environment
  CONTRIBUTING.md
Labels: documentation

#173 Implement social sign in on both server and client sides
  client/schema.graphql
  client/src/__generated__/SocialSignInButtonFacebookSignInMutation.graphql.ts
  client/src/__generated__/SocialSignInButtonGoogleSignInMutation.graphql.ts
  client/src/components/screen/VerifyEmail.tsx
  client/src/components/shared/SocialSignInButton.tsx
  client/src/types/graphql.ts
  client/web-build/register-service-worker.js
  server/src/utils/auth.ts
Labels: feature, integration
