Repository dooboolab/hackatalk, pull requests merged in 2020-05, with the labels that each got.

#126 Upgrade react-native to 0.62.2
  .circleci/config.yml
  .gitignore
  .ncurc.json
  android/app/build.gradle
  android/app/src/debug/java/com/hackatalk/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/dooboolab/hackatalk/MainActivity.java
  android/app/src/main/java/com/dooboolab/hackatalk/MainApplication.java
  android/app/src/main/java/com/dooboolab/hackatalk/generated/BasePackageList.java
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  index.js
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/HackaTalk.xcodeproj/xcshareddata/xcschemes/HackaTalk.xcscheme
  ios/HackaTalk/AppDelegate.h
  ios/HackaTalk/AppDelegate.m
  ios/HackaTalk/Images.xcassets/Contents.json
  ios/HackaTalk/Info.plist
  ios/HackaTalk/main.m
  ios/HackaTalkTests/HackaTalkTests.m
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  package.json
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  src/components/screen/SearchUser.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ChannelCreate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/WebView.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/CheckBox.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ErrorView.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/MessageListItem.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/UserListItem.test.tsx.snap
  test/jestSetup.js
  yarn.lock
Labels: upgrade

#129 Boot splash animation
  .circleci/config.yml
  .prettierrc.js
  __mocks__/react-native-bootsplash.ts
  __mocks__/react-native-reanimated.js
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/dooboolab/hackatalk/MainActivity.java
  android/app/src/main/java/com/dooboolab/hackatalk/MainApplication.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/BootSplash.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/SplashActivity.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/SplashModule.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/SplashPackage.java
  android/app/src/main/res/drawable/bootsplash.xml
  android/app/src/main/res/drawable/splash_background.xml
  android/app/src/main/res/drawable/splash_logo.png
  android/app/src/main/res/drawable/splash_text_1.png
  android/app/src/main/res/drawable/splash_text_2.png
  android/app/src/main/res/layout/view_splash.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/styles.xml
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/HackaTalk/AppDelegate.m
  ios/Podfile.lock
  package.json
  src/App.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/RootStackNavigator.tsx
  src/components/navigation/__tests__/RootStackNavigator.test.tsx
  src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  src/components/screen/SignIn/index.tsx
  src/components/screen/SignIn/mobile.tsx
  src/components/screen/__tests__/ChangePw.test.tsx
  src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  src/utils/splash.ts
  test/jestSetup.js
  yarn.lock
Labels: enhancement, feature

#130 Web support intl
  .gitignore
  babel.config.js
  metro.config.js
  package.json
  web-build/register-service-worker.js
  yarn.lock
Labels: feature, integration

#131 Upgrade packages
  .eslintrc.js
  README.md
  STRINGS.ts
  environment.d.ts
  package.json
  src/App.tsx
  src/apis/sample.ts
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  src/components/screen/ChangePw.tsx
  src/components/screen/Message.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/__tests__/Channel.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/graphql/mutations.ts
  src/utils/Styles.ts
  src/utils/__tests__/ImagePicker.test.ts
  test/testUtils.tsx
  yarn.lock
Labels: upgrade

#132 Refactor BootSplash.java class, Support android dark splash screen
  android/app/src/main/java/com/dooboolab/hackatalk/MainActivity.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/BootSplash.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/SplashActivity.java
  android/app/src/main/java/com/dooboolab/hackatalk/splash/SplashModule.java
  android/app/src/main/res/drawable-night/splash_background.xml
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
Labels: enhancement
