Repository dooboolab/hackatalk, pull requests merged in 2020-06, with the labels that each got.

#135 Remove apollo client
  CONTRIBUTING.md
  README.md
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/App.tsx
  src/apollo/Client.ts
  src/apollo/testClient.ts
  src/components/screen/ChangePw.tsx
  src/components/screen/FindPw.tsx
  src/components/screen/Friend.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/SignIn/index.tsx
  src/components/screen/SignUp.tsx
  src/components/screen/VerifyEmail.tsx
  src/components/screen/__tests__/ChangePw.test.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/VerifyEmail.test.tsx
  src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SearchUser.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  src/components/shared/ProfileModal.tsx
  src/components/shared/__tests__/ProfileModal.test.tsx
  src/components/shared/__tests__/__snapshots__/ProfileModal.test.tsx.snap
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/providers/index.tsx
  yarn.lock
Labels: migration

#137 [Feat] Relay Integration
  .eslintignore
  .gitignore
  babel.config.js
  codegen.yml
  environment.d.ts
  package.json
  relay.config.js
  schema.graphql
  src/App.tsx
  src/__generated__/AppUserQuery.graphql.ts
  src/__generated__/SignInEmailMutation.graphql.ts
  src/__generated__/VerifyEmailMutation.graphql.ts
  src/components/screen/ChannelCreate.tsx
  src/components/screen/Friend.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/Settings.tsx
  src/components/screen/SignIn/index.tsx
  src/components/screen/SignIn/mobile.tsx
  src/components/screen/SignIn/tablet.tsx
  src/components/screen/VerifyEmail.tsx
  src/components/screen/__tests__/ChangePw.test.tsx
  src/components/screen/__tests__/Channel.test.tsx
  src/components/screen/__tests__/Friend.test.tsx
  src/components/screen/__tests__/NotFound.test.tsx
  src/components/screen/__tests__/SearchUser.test.tsx
  src/components/screen/__tests__/Settings.test.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/SignUp.test.tsx
  src/components/screen/__tests__/VerifyEmail.test.tsx
  src/components/screen/__tests__/__snapshots__/Channel.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  src/components/shared/MessageListItem.tsx
  src/components/shared/ProfileModal.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  src/components/ui/Buttons.ts
  src/graphql/mutations.ts
  src/providers/AuthProvider.tsx
  src/providers/ProfileModalProvider.tsx
  src/providers/index.tsx
  src/relay/RelayEnvironment.ts
  src/relay/fetch.ts
  src/types/graphql.ts
  src/types/index.ts
  test/setupTest.js
  test/testUtils.tsx
  tsconfig.json
  yarn.lock
Labels: integration

#140 Upgrading packages and dooboo-ui migration
  ios/Podfile.lock
  jest.config.js
  package.json
  src/App.tsx
  src/components/navigation/AuthStackNavigator.tsx
  src/components/navigation/MainStackNavigator.tsx
  src/components/navigation/MainTabNavigator.tsx
  src/components/navigation/RootStackNavigator.tsx
  src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  src/components/screen/ChangePw.tsx
  src/components/screen/Channel.tsx
  src/components/screen/ChannelCreate.tsx
  src/components/screen/FindPw.tsx
  src/components/screen/Friend.tsx
  src/components/screen/Message.tsx
  src/components/screen/PinchZoomViewPager.tsx
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/SearchUser.tsx
  src/components/screen/Settings.tsx
  src/components/screen/SignIn/index.tsx
  src/components/screen/SignIn/mobile.tsx
  src/components/screen/SignIn/tablet.tsx
  src/components/screen/SignUp.tsx
  src/components/screen/VerifyEmail.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/__snapshots__/ChangePw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ChannelCreate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/FindPw.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Friend.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Message.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/Settings.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/SignUp.test.tsx.snap
  src/components/screen/__tests__/__snapshots__/VerifyEmail.test.tsx.snap
  src/components/shared/ChannelListItem.tsx
  src/components/shared/ErrorView.tsx
  src/components/shared/MessageListItem.tsx
  src/components/shared/ProfileModal.tsx
  src/components/shared/SearchTextInput.tsx
  src/components/shared/StatusBar.tsx
  src/components/shared/UserListItem.tsx
  src/components/shared/__tests__/__snapshots__/ErrorView.test.tsx.snap
  src/providers/__tests__/ThemeProvider.test.tsx
  src/providers/index.tsx
  src/styled.d.ts
  test/testUtils.tsx
  yarn.lock
Labels: migration

#141 Remove onesignal
  .circleci/config.yml
  .env.sample
  android/app/build.gradle
  android/app/src/main/java/com/dooboolab/hackatalk/MainApplication.java
  android/build.gradle
  android/settings.gradle
  environment.d.ts
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/HackaTalk/HackaTalk.entitlements
  ios/HackaTalk/Info.plist
  ios/OneSignalNotificationServiceExtension/Info.plist
  ios/OneSignalNotificationServiceExtension/NotificationService.h
  ios/OneSignalNotificationServiceExtension/NotificationService.m
  ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/App.tsx
  yarn.lock
Labels: migration

#142 Initial migration of social auth to expo-auth-sesssion
  .env.sample
  __mocks__/expo-facebook.ts
  __mocks__/expo-google-sign-in.ts
  android/app/src/main/AndroidManifest.xml
  app.json
  ios/HackaTalk-tvOS/Info.plist
  ios/HackaTalk.xcodeproj/project.pbxproj
  ios/HackaTalk/AppDelegate.m
  ios/HackaTalk/Info.plist
  ios/Podfile.lock
  package.json
  src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  src/components/screen/SignIn.tsx
  src/components/screen/SignIn/index.tsx
  src/components/screen/SignIn/tablet.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/VerifyEmail.test.tsx
  src/components/screen/__tests__/__snapshots__/SignIn.test.tsx.snap
  src/components/shared/SocialSignInButton.tsx
  src/components/shared/__tests__/SocialSignInButton.test.tsx
  src/components/shared/__tests__/__snapshots__/SocialSignInButton.test.tsx.snap
  src/types/graphql.ts
  yarn.lock
Labels: migration

#143 Test relay mutation in [SignIn] screen
  jest.config.js
  src/App.tsx
  src/__generated__/ProfileUpdateMeQuery.graphql.ts
  src/components/screen/ProfileUpdate.tsx
  src/components/screen/SignIn.tsx
  src/components/screen/__tests__/FindPw.test.tsx
  src/components/screen/__tests__/ProfileUpdate.test.tsx
  src/components/screen/__tests__/SignIn.test.tsx
  src/components/screen/__tests__/__snapshots__/ProfileUpdate.test.tsx.snap
  src/providers/index.tsx
  src/relay/fetch.ts
  src/types/graphql.ts
Labels: testing

#144 [Enhance] Update provider to reset relay env
  src/App.tsx
  src/providers/AuthProvider.tsx
  src/providers/index.tsx
  src/relay/RelayEnvironment.ts
  src/relay/environment.ts
  src/relay/fetch.ts
  src/relay/index.ts
  src/utils/relay.ts
  test/setupTest.js
Labels: enhancement

#149 Fix the error in validateCredential func by changing the dot('.') value in the hash
  server/src/utils/auth.ts
Labels: bugfix
