Repository dooboolab/hackatalk, pull requests merged in 2021-01, with the labels that each got.

#334 Enable Strict Mode for Typescript
  server/dotenv/test.env
  server/src/context.ts
  server/src/models/Channel.ts
  server/src/models/Scalar.ts
  server/src/models/User.ts
  server/src/resolvers/BlockedUser/mutation.ts
  server/src/resolvers/BlockedUser/query.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/resolvers/Channel/query.ts
  server/src/resolvers/Friend/mutation.ts
  server/src/resolvers/Friend/query.ts
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/Message/query.ts
  server/src/resolvers/Notification/mutation.ts
  server/src/resolvers/Notification/query.ts
  server/src/resolvers/Report/mutation.ts
  server/src/resolvers/Report/query.ts
  server/src/resolvers/User/mutation.ts
  server/src/resolvers/User/query.ts
  server/src/server.ts
  server/src/services/ChannelService.ts
  server/src/services/NotificationService.ts
  server/src/utils/assert.ts
  server/src/utils/auth.ts
  server/src/utils/azure.ts
  server/src/utils/filterNullProperties.ts
  server/tests/e2e/queries/Channel.ts
  server/tests/e2e/queries/User.ts
  server/tests/integration/tests/user.test.ts
  server/tsconfig.json
Labels: enhancement

#336 Applied more linting rules from @dooboo/eslint-config 0.6.5
  .circleci/config.yml
  client/.eslintrc.js
  client/package.json
  client/src/App.tsx
  client/src/components/navigation/MainStackNavigator.tsx
  client/src/components/navigation/__tests__/AuthStackNavigator.test.tsx
  client/src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  client/src/components/navigation/__tests__/__snapshots__/RootStackNavigator.test.tsx.snap
  client/src/components/screen/BlockedUser.tsx
  client/src/components/screen/ChangePw.tsx
  client/src/components/screen/Channel.tsx
  client/src/components/screen/ChannelCreate.tsx
  client/src/components/screen/ImageSlider.tsx
  client/src/components/screen/Message.tsx
  client/src/components/screen/ProfileUpdate.tsx
  client/src/components/screen/SearchUser.tsx
  client/src/components/screen/SignIn.tsx
  client/src/components/screen/SignUp.tsx
  client/src/components/screen/VerifyEmail.tsx
  client/src/components/screen/__tests__/ChangePw.test.tsx
  client/src/components/screen/__tests__/Channel.test.tsx
  client/src/components/screen/__tests__/ChannelCreate.test.tsx
  client/src/components/screen/__tests__/FindPw.test.tsx
  client/src/components/screen/__tests__/Friend.test.tsx
  client/src/components/screen/__tests__/Message.test.tsx
  client/src/components/screen/__tests__/ProfileUpdate.test.tsx
  client/src/components/screen/__tests__/SearchUser.test.tsx
  client/src/components/screen/__tests__/Settings.test.tsx
  client/src/components/screen/__tests__/SignIn.test.tsx
  client/src/components/screen/__tests__/SignUp.test.tsx
  client/src/components/shared/ChannelListItem.tsx
  client/src/components/shared/GiftedChat.tsx
  client/src/components/shared/MessageListItem.tsx
  client/src/components/shared/PinchZoom.tsx
  client/src/components/shared/ProfileModal.tsx
  client/src/components/shared/SocialSignInButton.tsx
  client/src/components/shared/TextInput.tsx
  client/src/components/shared/UserListItem.tsx
  client/src/components/shared/__tests__/GiftedChat.test.tsx
  client/src/components/shared/__tests__/MessageListItem.test.tsx
  client/src/components/shared/__tests__/ProfileModal.test.tsx
  client/src/hooks/useResponsiveDesign.tsx
  client/src/providers/AuthProvider.tsx
  client/src/relay/util.ts
  client/src/utils/ImagePicker.ts
  client/src/utils/noti.ts
Labels: enhancement, eslint

#337 Applied new eslint rules from @dooboo/eslint-config
  .circleci/config.yml
  client/README.md
  server/.eslintrc.js
  server/jest.config.js
  server/package.json
  server/src/apis/root.ts
  server/src/app.ts
  server/src/models/Scalar.ts
  server/src/models/User.ts
  server/src/permissions/index.ts
  server/src/resolvers/BlockedUser/mutation.ts
  server/src/resolvers/BlockedUser/query.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/resolvers/Channel/query.ts
  server/src/resolvers/Friend/query.ts
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/Message/query.ts
  server/src/resolvers/Report/mutation.ts
  server/src/resolvers/User/mutation.ts
  server/src/resolvers/User/query.ts
  server/src/schema.ts
  server/src/server.ts
  server/src/services/ChannelService.ts
  server/src/services/NotificationService.ts
  server/src/services/UserService.ts
  server/src/utils/assert.ts
  server/src/utils/auth.ts
  server/src/utils/azure.ts
  server/src/utils/error.ts
  server/src/utils/filterNullProperties.ts
  server/src/utils/pagination.ts
  server/tests/e2e/queries/Report.ts
  server/tests/integration/apis/UserAPI.ts
  server/tests/integration/apis/types.ts
  server/tests/integration/data/UserData.ts
  server/tests/integration/data/index.ts
  server/tests/integration/resolvers/User.ts
  server/tests/integration/resolvers/index.ts
  server/tests/integration/testServer.ts
  server/tests/integration/tests/user.test.ts
  server/tests/queries/BlockedUser.ts
  server/tests/queries/Channel.ts
  server/tests/queries/Friend.ts
  server/tests/queries/Message.ts
  server/tests/queries/Report.ts
  server/tests/queries/User.ts
  server/tests/queries/index.ts
  server/tests/resolvers/User/signInEmail.test.ts
  server/tests/resolvers/User/signInWithApple.test.ts
  server/tests/resolvers/User/signInWithFacebook.test.ts
  server/tests/resolvers/User/signInWithGoogle.test.ts
  server/tests/resolvers/blockedUser.test.ts
  server/tests/resolvers/channel.test.ts
  server/tests/resolvers/friend.test.ts
  server/tests/resolvers/message.test.ts
  server/tests/resolvers/report.test.ts
  server/tests/resolvers/upload.test.ts
  server/tests/resolvers/user.test.ts
  server/tests/testSetup.ts
  server/yarn.lock
Labels: eslint, server, testing

#338 Edit eslint config by updating @dooboo/eslint-config
  client/package.json
  client/src/apis/sample.ts
  client/src/apis/upload.ts
  client/src/components/screen/__tests__/Friend.test.tsx
  client/yarn.lock
Labels: eslint

#339 Fix Glob Pattern for ESLint in package.json
  server/package.json
  server/src/apis/root.ts
  server/src/models/Channel.ts
  server/tests/resolvers/user.test.ts
  server/yarn.lock
Labels: bugfix, eslint

#341 Updated packages
  client/src/utils/ImagePicker.ts
  client/src/utils/__tests__/ImagePicker.test.ts
  server/package.json
  server/yarn.lock
Labels: WIP, update packages

#344 Migrate azure blob storage to recent package
  server/__mocks__/azure-storage.ts
  server/__mocks__/multer-azure-blob-storage.ts
  server/package.json
  server/src/apis/root.ts
  server/src/resolvers/Upload/mutation.ts
  server/src/utils/azure.ts
  server/tests/resolvers/upload.test.ts
  server/yarn.lock
Labels: migration, server

#345 Client packages migration (dooboo-ui 0.0.34)
  client/.gitignore
  client/package.json
  client/src/components/navigation/AuthStackNavigator.tsx
  client/src/components/navigation/RootStackNavigator.tsx
  client/src/components/navigation/__tests__/__snapshots__/AuthStackNavigator.test.tsx.snap
  client/src/components/screen/ChangePw.tsx
  client/src/components/screen/Channel.tsx
  client/src/components/screen/ChannelCreate.tsx
  client/src/components/screen/FindPw.tsx
  client/src/components/screen/LicenseAgreement.tsx
  client/src/components/screen/Message.tsx
  client/src/components/screen/ProfileUpdate.tsx
  client/src/components/screen/Report.tsx
  client/src/components/screen/Settings.tsx
  client/src/components/screen/SignIn.tsx
  client/src/components/screen/SignUp.tsx
  client/src/components/screen/VerifyEmail.tsx
  client/src/components/screen/__tests__/SignIn.test.tsx
  client/src/components/screen/__tests__/SignUp.test.tsx
  client/src/components/shared/ChannelListItem.tsx
  client/src/components/shared/MessageListItem.tsx
  client/src/components/shared/SearchTextInput.tsx
  client/src/components/shared/TextInput.tsx
  client/src/components/shared/UserListItem.tsx
  client/src/theme.ts
  client/yarn.lock
  server/src/apis/root.ts
Labels: migration

#346 Path uploading and i18n linting
  client/.eslintrc.js
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/custom-syntax-validator.js
  client/package.json
  client/src/components/screen/Message.tsx
  client/yarn.lock
  server/package.json
  server/yarn.lock
Labels: client, enhancement, patch, server, update packages
