Repository dooboolab/hackatalk, pull requests merged in 2021-09, with the labels that each got.

#474 Add self chat feature
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/schema.graphql
  client/src/__generated__/ChannelCreateFriendsPaginationQuery.graphql.ts
  client/src/__generated__/ChannelCreate_friends.graphql.ts
  client/src/__generated__/Channels.graphql.ts
  client/src/__generated__/ChannelsQuery.graphql.ts
  client/src/__generated__/FriendFriendsPaginationQuery.graphql.ts
  client/src/__generated__/FriendsQuery.graphql.ts
  client/src/__generated__/MainChannelComponent_channel.graphql.ts
  client/src/__generated__/MainFriend_friends.graphql.ts
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/__generated__/UserUpdateProfileMutation.graphql.ts
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/navigations/__tests__/ProfileModal.test.tsx
  client/src/components/pages/ChannelCreate.tsx
  client/src/components/pages/MainChannel.tsx
  client/src/components/pages/MainFriend.tsx
  client/src/components/pages/__tests__/ChannelCreate.test.tsx
  client/src/components/pages/__tests__/MainChannel.test.tsx
  client/src/components/pages/__tests__/MainFriend.test.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/components/uis/UserListItem.tsx
  client/src/components/uis/__tests__/ChannelListItem.test.tsx
  client/src/providers/AuthProvider.tsx
  client/src/providers/ProfileModalProvider.tsx
  client/src/relay/queries/Friend.tsx
  client/src/relay/queries/Message.tsx
  client/src/relay/queries/User.tsx
  client/src/types/graphql.tsx
  server/prisma/migrations/20210823155817_add_channel_type_self/migration.sql
  server/prisma/schema.prisma
  server/src/models/Scalar.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/resolvers/Friend/query.ts
  server/src/services/ChannelService.ts
Labels: 🎯 feature

#480 Hotfix minor error in #474
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/uis/StatusMessageView.tsx
  client/src/components/uis/UserListItem.tsx
Labels: 🔥 hotfix

#472 Fix sign up status message
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/navigations/__tests__/ProfileModal.test.tsx
  client/src/components/pages/SignUp.tsx
  client/src/components/uis/StatusMessageView.tsx
  client/src/components/uis/__tests__/StatusMessageView.test.tsx
Labels: 🍗 enhancement

#484 enh: message option view and keyboard behavior
  client/.svgrrc
  client/assets/icons/arr_down.svg
  client/assets/icons/arr_up.svg
  client/assets/icons/msg_camera.png
  client/assets/icons/msg_camera@2x.png
  client/assets/icons/msg_camera@3x.png
  client/assets/icons/msg_file.png
  client/assets/icons/msg_file@2x.png
  client/assets/icons/msg_file@3x.png
  client/assets/icons/msg_image.png
  client/assets/icons/msg_image@2x.png
  client/assets/icons/msg_image@3x.png
  client/assets/icons/msg_mic.png
  client/assets/icons/msg_mic@2x.png
  client/assets/icons/msg_mic@3x.png
  client/assets/icons/msg_phone.png
  client/assets/icons/msg_phone@2x.png
  client/assets/icons/msg_phone@3x.png
  client/package.json
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/navigations/MainTabNavigator.tsx
  client/src/components/pages/Message.tsx
  client/src/components/uis/GiftedChat.tsx
  client/src/theme.ts
  client/src/utils/Icons.ts
  client/yarn.lock
Labels: 🍗 enhancement

#487 Enhance button design and new prettier conifg
  client/.prettierrc.js
  client/assets/icons/btn_send.svg
  client/src/App.tsx
  client/src/components/navigations/AuthStackNavigator.tsx
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/navigations/MainTabNavigator.tsx
  client/src/components/navigations/RootStackNavigator.tsx
  client/src/components/pages/ChangePw.tsx
  client/src/components/pages/ChannelCreate.tsx
  client/src/components/pages/ImageSlider.tsx
  client/src/components/pages/LicenseAgreement.tsx
  client/src/components/pages/MainChannel.tsx
  client/src/components/pages/Message.tsx
  client/src/components/pages/ProfileUpdate.tsx
  client/src/components/pages/Report.tsx
  client/src/components/pages/SearchUser.tsx
  client/src/components/pages/Settings.tsx
  client/src/components/pages/SignIn/index.tsx
  client/src/components/pages/SignUp.tsx
  client/src/components/pages/VerifyEmail.tsx
  client/src/components/pages/__tests__/Message.test.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/components/uis/CheckBox.tsx
  client/src/components/uis/CustomLoadingIndicator.tsx
  client/src/components/uis/EmptyListItem.tsx
  client/src/components/uis/GiftedChat.tsx
  client/src/components/uis/MessageListItem.tsx
  client/src/components/uis/PinchZoom.tsx
  client/src/components/uis/StatusMessageView.tsx
  client/src/components/uis/UserListItem.tsx
  client/src/providers/AuthProvider.tsx
  client/src/providers/DeviceProvider.tsx
  client/src/providers/ProfileModalProvider.tsx
  client/src/providers/SnackbarProvider.tsx
  client/src/theme.ts
  client/src/utils/Icons.ts
  server/.prettierrc.js
Labels: 🍗 enhancement, :abc: lint

#488 Remove nexus-plugin and upgrade pacakges (prisma 3.0.2)
  .circleci/config.yml
  server/.gitignore
  server/.ncurc.json
  server/jest.config.js
  server/package.json
  server/src/apis/root.ts
  server/src/models/BlockedUser.ts
  server/src/models/Channel.ts
  server/src/models/Friend.ts
  server/src/models/Membership.ts
  server/src/models/Message.ts
  server/src/models/Notification.ts
  server/src/models/Reaction.ts
  server/src/models/Reply.ts
  server/src/models/Report.ts
  server/src/models/User.ts
  server/src/resolvers/User/mutation.ts
  server/src/schema.ts
  server/src/server.ts
  server/src/utils/filterNullProperties.ts
  server/tests/resolvers/upload.test.ts
  server/tests/resolvers/user.test.ts
  server/tests/testSetup.ts
  server/tests/testUtils.ts
  server/tsconfig.json
  server/yarn.lock
  website/docs/server/installation.md
Labels: 🚽 migration, ☁️ server, 🗃 update packages

#489 Support docker images for client devs to start easily
  server/Dockerfile
  server/docker-compose.yml
  server/package.json
  server/src/context.ts
  server/yarn.lock
  website/docs/client/installation.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/installation.md
Labels: 🍗 enhancement, ☁️ server, :dolphin: docker

#491 Fix user model
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/relay/queries/Message.tsx
  server/package.json
  server/src/models/User.ts
Labels: 🛠 bugfix, 🔥 hotfix

#493 Remove RelayResettableProvider
  client/src/App.tsx
  client/src/providers/AuthProvider.tsx
  client/src/providers/ResettableProvider.tsx
  client/test/testUtils.tsx
Labels: 🍗 enhancement
