Repository dooboolab/hackatalk, pull requests merged in 2021-06, with the labels that each got.

#403 Optimistic Update After createMessage Mutation
  client/package.json
  client/src/components/pages/Message.tsx
  client/src/relay/updaters.tsx
  client/yarn.lock
Labels: 🍗 enhancement

#405 Fix Multiple Device Self Message Issue
  client/src/relay/updaters.tsx
  server/src/resolvers/Message/subscription.ts
Labels: 🛠 bugfix

#406 Migrate `dooboo-ui` to v2 which starts from `0.1.0`
  client/package.json
  client/src/App.tsx
  client/src/components/navigations/RootStackNavigator.tsx
  client/src/components/pages/ChangePw.tsx
  client/src/components/pages/FindPw.tsx
  client/src/components/pages/Message.tsx
  client/src/components/pages/ProfileUpdate.tsx
  client/src/components/pages/Report.tsx
  client/src/components/pages/Settings.tsx
  client/src/components/pages/SignIn/SocialSignInButton.tsx
  client/src/components/pages/SignIn/index.tsx
  client/src/components/pages/SignUp.tsx
  client/src/components/pages/__tests__/SignIn.test.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/components/uis/SearchTextInput.tsx
  client/src/components/uis/StatusBar.tsx
  client/src/components/uis/UserListItem.tsx
  client/test/testUtils.tsx
  client/yarn.lock
Labels: 📱 client, 🚽 migration

#407 Add [deviceKey] Arg for Filtering Subscriptions
  client/schema.graphql
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/pages/Message.tsx
  client/src/providers/DeviceProvider.tsx
  client/src/relay/queries/Message.tsx
  client/src/types/graphql.tsx
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/Message/subscription.ts
  server/tests/queries/Message.ts
  server/tests/resolvers/message.test.ts
Labels: 🛠 bugfix

#409 Group newly created messages with dates
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/relay/queries/Message.tsx
  client/src/relay/updaters.tsx
Labels: 🍗 enhancement, 🔥 hotfix

#411 Load More Messages When Going Foreground
  client/src/components/pages/Message.tsx
  client/src/hooks/useAppState.tsx
  client/src/hooks/useAppStateChangeHandler.tsx
  client/src/hooks/useOrientation.tsx
Labels: 🍗 enhancement

#410 Release 1.7.0
  client/app.config.ts
  client/package.json
Labels: 📘 release, 📱 iOS, 🤖 android

#414 Wrap navigation `setOption` in useLayoutEffect
  client/src/components/pages/ChannelCreate.tsx
  client/src/components/pages/LicenseAgreement.tsx
  client/src/components/pages/Message.tsx
  client/src/components/pages/SearchUser.tsx
Labels: 🍗 enhancement, 📱 client

#417 Update website on installation and contributing
  .github/workflows/deploy-website.yml
  CONTRIBUTING.md
  client/.dooboo/v5
  client/src/components/uis/MessageListItem.tsx
  website/docs/client/components.md
  website/docs/client/installation.md
  website/docs/client/overview.md
  website/docs/implementation/stackshare.md
  website/docs/server/installation.md
  website/docs/server/message.md
  website/docs/server/overview.md
  website/docs/server/specification.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/components.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/installation.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/overview.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/implementation/stackshare.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/installation.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/overview.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/specification.md
  website/package.json
  website/sidebars.js
  website/static/img/dooboo-cli-5.png
  website/static/img/nested-navigation-structure.png
Labels: 📖 documentation

#418 Add Korean translation in `website`
  website/docs/implementation/authentication.md
  website/docs/implementation/design.md
  website/docs/implementation/stackshare.md
  website/docs/server/channel.md
  website/i18n/ko/docusaurus-plugin-content-blog/2019-12-07-dooboo-cli.md
  website/i18n/ko/docusaurus-plugin-content-blog/2019-12-08-react-navigation-v5.md
  website/i18n/ko/docusaurus-plugin-content-blog/2020-06-19-prisma2-migration.md
  website/i18n/ko/docusaurus-plugin-content-blog/2020-06-24-integrate-relay.md
  website/i18n/ko/docusaurus-plugin-content-blog/2020-07-12-setup-postgresql-prisma2.md
  website/i18n/ko/docusaurus-plugin-content-blog/2021-05-24-announcing-wehack.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/components.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/installation.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/integrate-with-backend.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/overview.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/search-users.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/client/start-direct-messaging.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/implementation/authentication.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/implementation/design.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/implementation/features.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/implementation/pagination.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/implementation/stackshare.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/channel.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/installation.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/membership.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/message.md
  website/i18n/ko/docusaurus-plugin-content-docs/current/server/overview.md
Labels: :kr: translation, 🕸 website
