Repository dooboolab/hackatalk, pull requests merged in 2021-08, with the labels that each got.

#443 Bugfix url handling bug on logout [Web]
  client/src/providers/AuthProvider.tsx
Labels: 🛠 bugfix

#444 Add membership number circle
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/uis/ChannelListItem.tsx
  server/src/models/Channel.ts
  server/src/resolvers/Message/mutation.ts
Labels: 🎯 feature

#456 Add clickable Links/URL
  client/package.json
  client/src/components/uis/MessageListItem.tsx
  client/src/theme.ts
  client/yarn.lock
Labels: 🍗 enhancement, 🎯 feature

#460 Navigate to [LicenseAgreement] only in `iOS`
  client/src/components/pages/LicenseAgreement.tsx
  client/src/components/pages/SignIn/index.tsx
Labels: 🔥 hotfix

#461 [FindPw] Improve the coverage of `FindPw` page
  client/src/components/pages/__tests__/FindPw.test.tsx
Labels: 🍗 enhancement

#457 Fix profile status message overflow & subscription
  client/package.json
  client/src/__generated__/MainFriendUserUpdatedSubscription.graphql.ts
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/__generated__/MainStackNavigatorUserUpdatedSubscription.graphql.ts
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/navigations/__tests__/ProfileModal.test.tsx
  client/src/components/pages/MainFriend.tsx
  client/src/components/pages/ProfileUpdate.tsx
  client/src/components/uis/StatusMessageView.tsx
  client/src/components/uis/UserListItem.tsx
  client/src/components/uis/__tests__/StatusMessageView.test.tsx
  client/test/timeTravel.ts
  client/yarn.lock
  server/src/resolvers/User/subscription.ts
Labels: 🎯 feature

#464 Reset migration to point to schema `public`
  server/prisma/migrations/20210330100409_fix_schema/migration.sql
  server/prisma/migrations/20210701131023_replies_typo/migration.sql
  server/prisma/migrations/20210823034955_init/migration.sql
Labels: 🚽 migration

#465 Release 1.9.0 and packages migration
  client/__mocks__/@react-native-async-storage/async-storage.js
  client/jest.config.js
  client/package.json
  client/test/jestSetup.ts
  client/test/setupTest.ts
  client/webpack.config.js
  client/yarn.lock
  server/package.json
  server/yarn.lock
Labels: 🚽 migration, 📘 release

#467 Submit editing when `return` pressed
  client/src/components/pages/Message.tsx
  client/src/components/uis/GiftedChat.tsx
  client/src/hooks/useOrientation.tsx
Labels: 🍗 enhancement

#469 Bugfix - Generate Relay
  client/src/__generated__/AuthProviderMeQuery.graphql.ts
  client/src/__generated__/BlockedUserCreateMutation.graphql.ts
  client/src/__generated__/BlockedUserDeleteMutation.graphql.ts
  client/src/__generated__/ChannelCreateFriendsPaginationQuery.graphql.ts
  client/src/__generated__/ChannelCreate_friends.graphql.ts
  client/src/__generated__/ChannelFindOrCreatePrivateChannelMutation.graphql.ts
  client/src/__generated__/ChannelQuery.graphql.ts
  client/src/__generated__/Channels.graphql.ts
  client/src/__generated__/ChannelsQuery.graphql.ts
  client/src/__generated__/FriendAddMutation.graphql.ts
  client/src/__generated__/FriendDeleteMutation.graphql.ts
  client/src/__generated__/FriendFriendsPaginationQuery.graphql.ts
  client/src/__generated__/FriendsQuery.graphql.ts
  client/src/__generated__/MainChannelComponent_channel.graphql.ts
  client/src/__generated__/MainFriendUserUpdatedSubscription.graphql.ts
  client/src/__generated__/MainFriend_friends.graphql.ts
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/__generated__/MainStackNavigatorUserUpdatedSubscription.graphql.ts
  client/src/__generated__/MessageComponent_message.graphql.ts
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/__generated__/MessageLastMessageQuery.graphql.ts
  client/src/__generated__/MessageListItemTestQuery.graphql.ts
  client/src/__generated__/MessageListItem_message.graphql.ts
  client/src/__generated__/MessagePaginationQuery.graphql.ts
  client/src/__generated__/MessagesQuery.graphql.ts
  client/src/__generated__/NotificationCreateNotificationMutation.graphql.ts
  client/src/__generated__/NotificationDeleteNotificationMutation.graphql.ts
  client/src/__generated__/ProfileModalTestQuery.graphql.ts
  client/src/__generated__/ProfileModal_user.graphql.ts
  client/src/__generated__/ReportCreateReportMutation.graphql.ts
  client/src/__generated__/SearchUserComponent_user.graphql.ts
  client/src/__generated__/SearchUsersQuery.graphql.ts
  client/src/__generated__/UploadSingleUploadMutation.graphql.ts
  client/src/__generated__/UserBlockedUsersQuery.graphql.ts
  client/src/__generated__/UserChangeEmailPasswordMutation.graphql.ts
  client/src/__generated__/UserFacebookSignInMutation.graphql.ts
  client/src/__generated__/UserFindPwMutation.graphql.ts
  client/src/__generated__/UserGoogleSignInMutation.graphql.ts
  client/src/__generated__/UserListItemTestQuery.graphql.ts
  client/src/__generated__/UserListItem_user.graphql.ts
  client/src/__generated__/UserMeQuery.graphql.ts
  client/src/__generated__/UserSignInAppleMutation.graphql.ts
  client/src/__generated__/UserSignInEmailMutation.graphql.ts
  client/src/__generated__/UserSignUpMutation.graphql.ts
  client/src/__generated__/UserUpdateProfileMutation.graphql.ts
  client/src/__generated__/UserUsersPaginationQuery.graphql.ts
  client/src/__generated__/UserVerifyEmailMutation.graphql.ts
  client/src/components/pages/Message.tsx
  client/src/components/uis/MessageListItem.tsx
  client/web-build/register-service-worker.js
Labels: 🛠 bugfix, 🏃 relay

#470 Add result message when updating profile
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/src/App.tsx
  client/src/components/pages/ProfileUpdate.tsx
  client/src/providers/SnackbarProvider.tsx
  client/src/providers/index.tsx
Labels: 🎯 feature

#475 Match the unity of the code
  client/src/theme.ts
Labels: :ant: minor fixes

#477 Fix subscription error when user sign out
  client/src/components/navigations/MainStackNavigator/index.tsx
Labels: 🔥 hotfix
