Repository dooboolab/hackatalk, pull requests merged in 2021-04, with the labels that each got.

#371 Fix wrong prisma schema
  server/package.json
  server/prisma/migrations/20210330100409_fix_schema/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/src/resolvers/Channel/mutation.ts
  server/src/resolvers/Report/query.ts
  server/src/resolvers/User/mutation.ts
  server/src/utils/auth.ts
  server/tests/resolvers/User/signInWithFacebook.test.ts
  server/yarn.lock
Labels: ☁️ server, 🍗 enhancement

#372 Upgrade expo sdk 41
  client/.ncurc.json
  client/config.ts
  client/package.json
  client/src/components/uis/SearchTextInput.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: 📱 client, 🚽 migration

#373 Remove expo-permissions from package.json due to deprecation
  client/package.json
  client/src/components/pages/__tests__/Message.test.tsx
  client/src/components/pages/__tests__/ProfileUpdate.test.tsx
  client/src/utils/ImagePicker.ts
  client/src/utils/__tests__/ImagePicker.test.ts
  client/src/utils/noti.ts
Labels: 🍗 enhancement, 📱 client, 🚽 migration

#374 Migrate style to emotion
  client/README.md
  client/babel.config.js
  client/package.json
  client/src/components/navigations/MainStackNavigator/ProfileModal.tsx
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/pages/BlockedUser.tsx
  client/src/components/pages/ChangePw.tsx
  client/src/components/pages/ChannelCreate.tsx
  client/src/components/pages/FindPw.tsx
  client/src/components/pages/ImageSlider.tsx
  client/src/components/pages/LicenseAgreement.tsx
  client/src/components/pages/MainChannel.tsx
  client/src/components/pages/MainFriend.tsx
  client/src/components/pages/Message.tsx
  client/src/components/pages/NotFound.tsx
  client/src/components/pages/ProfileUpdate.tsx
  client/src/components/pages/Report.tsx
  client/src/components/pages/SearchUser.tsx
  client/src/components/pages/Settings.tsx
  client/src/components/pages/SignIn/index.tsx
  client/src/components/pages/SignUp.tsx
  client/src/components/pages/VerifyEmail.tsx
  client/src/components/pages/WebView.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/components/uis/CheckBox.tsx
  client/src/components/uis/ErrorView.tsx
  client/src/components/uis/GiftedChat.tsx
  client/src/components/uis/MessageListItem.tsx
  client/src/components/uis/SearchTextInput.tsx
  client/src/components/uis/TextInput.tsx
  client/src/components/uis/UserListItem.tsx
  client/src/styled.d.ts
  client/test/setupTest.js
  client/tsconfig.json
  client/yarn.lock
Labels: 🚽 migration

#376 Add ability to add profile image during sign up
  client/README.md
  client/app.config.js
  client/config.ts
  client/schema.graphql
  client/src/__generated__/UserSignUpMutation.graphql.ts
  client/src/components/pages/ProfileUpdate.tsx
  client/src/components/pages/SignIn/SocialSignInButton.tsx
  client/src/components/pages/SignUp.tsx
  client/src/components/pages/VerifyEmail.tsx
  client/src/relay/fetch.ts
  client/src/relay/queries/User.tsx
  client/src/types/graphql.tsx
  client/src/utils/const.ts
  client/test/jestSetup.ts
  server/package.json
  server/src/resolvers/User/mutation.ts
  server/yarn.lock
Labels: 🍗 enhancement, 🎯 feature

#377 Fix Broken Message Layout
  client/src/components/pages/Message.tsx
  client/src/components/uis/MessageListItem.tsx
Labels: 🔥 hotfix

#378 Make Text Message Selectable
  client/src/components/uis/GiftedChat.tsx
  client/src/components/uis/MessageListItem.tsx
Labels: 🍗 enhancement
