Repository dooboolab/hackatalk, pull requests merged in 2021-10, with the labels that each got.

#495 Remove an unnessary AuthProviderOnly navigator
  client/src/App.tsx
  client/src/components/navigations/AuthStackNavigator.tsx
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/navigations/RootStackNavigator.tsx
  client/src/providers/AuthProvider.tsx
Labels: 🍗 enhancement, 🔧 refactor

#492 feat: Integrate leave channel resolver in client
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/src/__generated__/ChannelLeaveChannelMutation.graphql.ts
  client/src/components/navigations/MainStackNavigator/LeaveChannelModal.tsx
  client/src/components/navigations/MainStackNavigator/index.tsx
  client/src/components/pages/MainChannel.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/providers/LeaveChannelModalProvider.tsx
  client/src/providers/index.tsx
  client/src/relay/queries/Channel.tsx
  client/src/relay/updaters.tsx
  client/src/theme.ts
  server/src/models/Channel.ts
  server/src/resolvers/Channel/mutation.ts
  server/src/services/ChannelService.ts
Labels: 🎯 feature

#496 patch: Filter user channels with memberships count
  client/schema.graphql
  client/src/__generated__/AuthProviderMeQuery.graphql.ts
  client/src/__generated__/ChannelFindOrCreatePrivateChannelMutation.graphql.ts
  client/src/__generated__/ChannelLeaveChannelMutation.graphql.ts
  client/src/__generated__/MainChannelComponent_channel.graphql.ts
  client/src/__generated__/MainStackNavigatorOnMessageSubscription.graphql.ts
  client/src/__generated__/MessageCreateMutation.graphql.ts
  client/src/__generated__/MessageListItemTestQuery.graphql.ts
  client/src/__generated__/MessageListItem_message.graphql.ts
  client/src/__generated__/MessagePaginationQuery.graphql.ts
  client/src/__generated__/MessagesQuery.graphql.ts
  client/src/__generated__/ProfileModalTestQuery.graphql.ts
  client/src/__generated__/ReportCreateReportMutation.graphql.ts
  client/src/__generated__/UserFacebookSignInMutation.graphql.ts
  client/src/__generated__/UserGoogleSignInMutation.graphql.ts
  client/src/__generated__/UserListItemTestQuery.graphql.ts
  client/src/__generated__/UserMeQuery.graphql.ts
  client/src/__generated__/UserSignInAppleMutation.graphql.ts
  client/src/__generated__/UserSignInEmailMutation.graphql.ts
  client/src/components/pages/SignIn/SocialSignInButton.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/components/uis/MessageListItem.tsx
  client/src/types/graphql.tsx
  server/src/resolvers/Channel/query.ts
  server/tests/resolvers/channel.test.ts
Labels: 🍗 enhancement, :adhesive_bandage: patch

#494 feat: Video message
  client/.vscode/settings.json
  client/__mocks__/expo-av.ts
  client/__mocks__/expo-video-thumbnails.ts
  client/app.config.ts
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/package.json
  client/src/__generated__/MessageComponent_message.graphql.ts
  client/src/__generated__/MessagePaginationQuery.graphql.ts
  client/src/__generated__/MessagesQuery.graphql.ts
  client/src/apis/upload.ts
  client/src/components/pages/Message.tsx
  client/src/components/pages/ProfileUpdate.tsx
  client/src/components/pages/SignUp.tsx
  client/src/components/pages/__tests__/Message.test.tsx
  client/src/components/uis/ChannelListItem.tsx
  client/src/components/uis/MessageListItem.tsx
  client/src/components/uis/VideoPlayer.tsx
  client/src/components/uis/__tests__/ChannelListItem.test.tsx
  client/src/components/uis/__tests__/MessageListItem.test.tsx
  client/src/components/uis/__tests__/VideoPlayer.test.tsx
  client/src/utils/ImagePicker.ts
  client/src/utils/__tests__/ImagePicker.test.ts
  client/src/utils/const.ts
  client/yarn.lock
  server/locales/en.json
  server/locales/ko.json
  server/package.json
  server/src/apis/root.ts
  server/src/resolvers/Message/mutation.ts
  server/src/resolvers/Upload/mutation.ts
  server/src/resolvers/User/mutation.ts
  server/src/utils/azure.ts
  server/src/utils/const.ts
  server/tests/resolvers/upload.test.ts
  server/yarn.lock
Labels: 🎯 feature
