Repository dooboolab/hackatalk, pull requests merged in 2022-06, with the labels that each got.

#557 Migrate subscription to graphql-ws
  server/package.json
  server/src/context.ts
  server/src/server.ts
  server/yarn.lock
Labels: 🚽 migration

#558 Migrate client subscription-transport-ws to graphql-ws
  .github/workflows/deploy-server.yml
  .github/workflows/release-server.yml
  client/package.json
  client/src/components/pages/__tests__/ChannelCreate.test.tsx
  client/src/components/pages/__tests__/__snapshots__/MainChannel.test.tsx.snap
  client/src/components/pages/__tests__/__snapshots__/Message.test.tsx.snap
  client/src/components/uis/__tests__/MessageListItem.test.tsx
  client/src/components/uis/__tests__/StatusMessageView.test.tsx
  client/src/components/uis/__tests__/__snapshots__/ChannelListItem.test.tsx.snap
  client/src/relay/index.ts
  client/src/relay/subscription.ts
  client/test/jestSetup.js
  client/test/setupTest.ts
  client/yarn.lock
  server/package.json
  server/tests/testSetup.ts
  server/tests/testUtils.ts
  server/yarn.lock
Labels: 🚽 migration, 🧪 test, 📱 client

#561 Set up eas build & submit
  client/.gitignore
  client/.watchmanconfig
  client/eas.json
  client/package.json
Labels: 💨 ci, 🎯 feature

#563 Implement delete user mutation
  server/src/resolvers/User/mutation.ts
  server/tests/queries/User.ts
  server/tests/resolvers/user.test.ts
Labels: 🎯 feature

#564 Implement delete account button in settings
  client/assets/langs/en.json
  client/assets/langs/ko.json
  client/schema.graphql
  client/src/__generated__/UserDeleteUserMutation.graphql.ts
  client/src/components/pages/Settings.tsx
  client/src/components/pages/__tests__/__snapshots__/Settings.test.tsx.snap
  client/src/relay/queries/User.tsx
Labels: 🎯 feature, 📱 client
